### ISSUE TITLE
Do you guys have a English version of you paper?

### ISSUE THREAD

**Issue by jerrypy** [polcak/pcf#4]
I can't read Czech, if you do have an English version, can you send me a copy?

**Comment by jerrypy** [comment]
For anyone also wants an English version, below is a mail that the author replied to me:

Hello,

the diploma thesis of Jakub Jirásek is not available in English. However, at least two persons were able to use Google translator in the past.

Anyway, I suggest that you read my Ph.D. thesis (which is in English) instead. See https://www.fit.vutbr.cz/study/DP/PD.php.en?id=679&file=t (chapter 7). There, you can also find many references to a related bibliography of our research group as well as others.

**Comment by polcak** [comment]
More publications added to README
